#!/bin/bash
X="$(cat)"
echo -n "$X " # Try Shift+F5 here.

clear
echo "1) Move here and press F5." |
tr [a-z] [A-Z]
echo "2) Move here and press F5."
echo "3) Notice any difference?"

echo "note: look at stdout."

