######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 23 19:54:48 2011
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR=crumbs
#RCC_DIR=crumbs
MOC_DIR=crumbs

# Input
SOURCES += *.cpp
HEADERS += *.h
#RESOURCES += resources.qrc
